export default [
  {
    leadId: "QLHL000001",
    firstName: "Amit",
    lastName: "Sharma",
    email: "amit.sharma@email.com",
    phone: "+91 9876543210",
    loanType: "Home Loan",
    loanAmount: "₹35L",
    city: "Mumbai",
    status: "New",
    lastActivity: "2 hours ago",
    aiScore: 92,
    nextAction: "Call Immediately",
  },
  {
    leadId: "QLHL000002",
    firstName: "Priya",
    lastName: "Patel",
    email: "priya@email.com",
    phone: "+91 9876543211",
    loanType: "LAP",
    loanAmount: "₹25L",
    city: "Delhi",
    status: "Contacted",
    lastActivity: "1 hour ago",
    aiScore: 85,
    nextAction: "Send Proposal",
  },
  {
    leadId: "QLHL000003",
    firstName: "Rahul",
    lastName: "Verma",
    loanType: "Balance Transfer",
    loanAmount: "₹45L",
    city: "Bangalore",
    status: "Qualified",
    lastActivity: "30 min ago",
    aiScore: 78,
    nextAction: "Collect Documents",
  },
];
